Repository Ashraf-Alshashaa/Trade-Hub, pull requests merged in 2024-05, with the labels that each got.

#2 Sprint 1
  .idea/Trade-Hub.iml
  .idea/misc.xml
  db/models.py
Labels: not ready

#3 Init fastapi
  .gitignore
  main.py
Labels: under review

#16 Create get product
  db/db_product.py
  main.py
  routers/product.py
Labels: under review

#27 Move all bids for product to bid section.
  db/db_bid.py
  db/db_product.py
  routers/__init__.py
  routers/bid_router.py
  routers/product_router.py
  schemas/product.py
Labels: under review

#37 Added authentication to some routers
  routers/__init__.py
  routers/bid_router.py
  routers/product_router.py
  routers/user_router.py
Labels: under review

#39 The very last change
  db/db_bid.py
  db/db_product.py
  db/db_user.py
  routers/bid_router.py
  routers/product_router.py
  routers/user_router.py
Labels: under review

#43 Fix the change_bid_status. Only the seller can change the bid status …
  db/db_bid.py
  db/db_product.py
  db/db_user.py
  routers/__init__.py
  routers/bid_router.py
  routers/product_router.py
  routers/user_router.py
  run_seed_db.py
  seed_db/fake_data/__init__.py
  seed_db/fake_data/addresses_data.py
  seed_db/fake_data/bids_data.py
  seed_db/fake_data/products_data.py
  seed_db/fake_data/users_data.py
  seed_db/operations/__init__.py
  seed_db/operations/addresses.py
  seed_db/operations/bids.py
  seed_db/operations/products.py
  seed_db/operations/users.py
Labels: under review

#38 Create my sellling and buying sections
  db/__init__.py
  db/db_product.py
  routers/product_router.py
Labels: under review

#55 Fixed bid schema and fixed "add/get/get all" for bids
  db/db_bid.py
  routers/bid_router.py
  schemas/bid.py
  seed_db/fake_data/bids_data.py
Labels: ready to merge

#59 fixed get_cart
  db/db_product.py
  routers/product_router.py
Labels: ready to merge

#58 Create search products feature
  db/db_bid.py
  db/db_product.py
  db/models.py
  main.py
  routers/bid_router.py
  routers/product_router.py
  schemas/bid.py
  schemas/product.py
  seed_db/fake_data/bids_data.py
  seed_db/fake_data/products_data.py
  seed_db/operations/products.py
Labels: under review

#54 Added the relational statements to our models.py.
  db/models.py
Labels: ready to merge
