Repository Ashraf-Alshashaa/Trade-Hub, pull requests merged in 2024-06, with the labels that each got.

#63 Fix add get product
  db/db_product.py
  routers/product_router.py
Labels: under review

#73 Create payments
  .idea/misc.xml
  db/db_bid.py
  db/db_product.py
  db/models.py
  main.py
  requirements.txt
  routers/payments_router.py
  schemas/__init__.py
  schemas/payments.py
  seed_db/fake_data/bids_data.py
  seed_db/fake_data/products_data.py
Labels: under review

#66 Fix username uniqueness
  .idea/misc.xml
  db/__init__.py
  db/db_user.py
  db/models.py
Labels: under review

#68 Created filter products by categories
  auth/authentication.py
  db/db_category.py
  db/db_product.py
  db/models.py
  main.py
  routers/category_router.py
  routers/product_router.py
  run_seed_db.py
  schemas/category.py
  schemas/users.py
  seed_db/fake_data/categories_data.py
  seed_db/fake_data/products_data.py
  seed_db/fake_data/users_data.py
  seed_db/operations/products.py
  seed_db/operations/users.py
Labels: under review

#81 Fix return status code 204 after deleting
  routers/category_router.py
  routers/product_router.py
  routers/user_address_router.py
  routers/user_router.py
Labels: under review

#82 Fix get user path id
  routers/user_router.py
Labels: under review

#85 Fix change payment status
  db/db_payment.py
  routers/payments_router.py
  schemas/payments.py
Labels: ready to merge

#83 address ID path parameter fix
  db/db_user.py
  db/db_user_address.py
  routers/user_address_router.py
  routers/user_router.py
  schemas/user_address.py
  schemas/users.py
Labels: under review

#86 Fix change bid
  db/db_bid.py
  db/db_product.py
  routers/bid_router.py
  routers/product_router.py
Labels: under review

#89 removed the 404 exceptions, improved the design of get_product.
  db/db_product.py
  db/db_user.py
  routers/product_router.py
Labels: changes after front end
